# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=snapbin

server.port=8080

file.storage.local-path=./snapbin_storage
file.access.base-url=http://localhost:8080


# JWT token configs
jwt.secret=Ykdu2Vqu3PQX7JOp6L9sXm1EqVpHVzrWc2Kt3OBUHd94DpFtHn9k9A2T4rP56Vpu
jwt.expiration=3600000


# Security default creds
spring.security.user.name=admin
spring.security.user.password=admin123

# Swagger
springfox.documentation.swagger.v2.path=/api-docs
